### ISSUE TITLE
请问如何做重复动画；

### ISSUE THREAD

**Issue by zhuoshirong** [wisdomtl/FrameSurfaceView#1]

**Comment by wisdomtl** [comment]
增加了接口`setRepeatTimes()`，详见 3ffde99 这次commit

**Comment by StaticCoder** [comment]
需要修改framesurfaceview里的index，在最后一帧播完的时候，把index归零，就能做到无缝循环了。作者原本的代码虽然也能循环，但是会有明显的卡顿。
